# Generated by Django 4.2.4 on 2023-08-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('team', 'Team'), ('voter', 'Voter')], max_length=255, null=True),
        ),
    ]
