# Generated by Django 4.2.4 on 2023-08-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_area_code_alter_user_identity_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('team', 'Team'), ('voter', 'Voter'), ('candidate', 'Candidate'), ('chairmen', 'Chairmen')], max_length=255, null=True),
        ),
    ]
